//! Property test generation pass.
//!
//! Generates test functions from SPL `prop` and `examples` constructs
//! that have been lowered to Core IR. This module provides:
//! - Extraction of test functions from a module
//! - Generation of property-based test harness entries
//! - Oracle differential testing setup (reference vs optimized)
//! - Requirement coverage tracking

use speclang_ir::expr::{BinOp, Block, Expr, Stmt};
use speclang_ir::module::{Annotation, Function, Module, Param};
use speclang_ir::types::Type;

/// A generated test case.
#[derive(Debug, Clone)]
pub struct TestCase {
    /// The name of the generated test function.
    pub name: String,
    /// The source function being tested (if applicable).
    pub source_function: Option<String>,
    /// The kind of test.
    pub kind: TestKind,
    /// Requirement tags covered by this test.
    pub req_tags: Vec<String>,
    /// The generated test function.
    pub function: Function,
}

/// What kind of test was generated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TestKind {
    /// From an SPL `examples` block.
    Example,
    /// From an SPL `prop` block.
    Property,
    /// Oracle differential test.
    Oracle,
}

/// Extract all test functions from a module.
///
/// Test functions are those whose names start with `test_` or `prop_`
/// (generated by SPL lowering from `examples` and `prop` blocks).
pub fn extract_tests(module: &Module) -> Vec<TestCase> {
    let mut tests = Vec::new();

    for func in &module.functions {
        if func.name.starts_with("test_") {
            let source = extract_source_function_name(&func.name, "test_");
            let req_tags = extract_req_tags(&func.annotations);
            tests.push(TestCase {
                name: func.name.clone(),
                source_function: source,
                kind: TestKind::Example,
                req_tags,
                function: func.clone(),
            });
        } else if func.name.starts_with("prop_") {
            let source = extract_source_function_name(&func.name, "prop_");
            let req_tags = extract_req_tags(&func.annotations);
            tests.push(TestCase {
                name: func.name.clone(),
                source_function: source,
                kind: TestKind::Property,
                req_tags,
                function: func.clone(),
            });
        }
    }

    tests
}

/// Generate an oracle differential test for a function that has both
/// a reference and optimized implementation.
///
/// The oracle test calls both implementations with the same inputs
/// and asserts that their outputs are equal.
pub fn generate_oracle_test(
    func_name: &str,
    reference_name: &str,
    params: &[Param],
    _return_type: &Type,
) -> Function {
    let test_name = format!("oracle_{}", func_name);

    // Build: assert(func(args...) == reference(args...), "oracle mismatch")
    let args: Vec<Expr> = params
        .iter()
        .map(|p| Expr::Var(p.name.clone()))
        .collect();

    let call_func = Expr::Call {
        func: vec![func_name.to_string()],
        args: args.clone(),
    };

    let call_reference = Expr::Call {
        func: vec![reference_name.to_string()],
        args,
    };

    let assertion = Stmt::Assert {
        cond: Expr::BinOp {
            op: BinOp::Eq,
            lhs: Box::new(call_func),
            rhs: Box::new(call_reference),
        },
        message: format!(
            "oracle mismatch: {}(...) != {}(...)",
            func_name, reference_name
        ),
    };

    Function {
        name: test_name,
        params: params.to_vec(),
        return_type: Type::unit(),
        effects: vec![],
        contracts: vec![],
        body: Block {
            stmts: vec![assertion],
            expr: None,
        },
        annotations: vec![],
    }
}

/// Generate a test harness module from extracted tests.
///
/// The harness module contains wrapper functions that backends can use
/// to drive property-based testing with random inputs.
pub fn generate_test_harness(
    module_name: &[String],
    tests: &[TestCase],
) -> Module {
    let mut harness_name: Vec<String> = module_name.to_vec();
    harness_name.push("tests".to_string());
    let mut harness = Module::new(harness_name);

    for test in tests {
        harness.functions.push(test.function.clone());
    }

    harness
}

/// Collect requirement coverage: map from req tag → list of test names.
pub fn requirement_coverage(tests: &[TestCase]) -> Vec<(String, Vec<String>)> {
    let mut coverage: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();

    for test in tests {
        for tag in &test.req_tags {
            coverage
                .entry(tag.clone())
                .or_default()
                .push(test.name.clone());
        }
    }

    coverage.into_iter().collect()
}

/// Find functions that have oracle annotations.
///
/// Returns (function_name, reference_function_name) pairs.
pub fn find_oracle_pairs(module: &Module) -> Vec<(String, String)> {
    let mut pairs = Vec::new();
    for func in &module.functions {
        for ann in &func.annotations {
            if let Annotation::Id(id) = ann {
                if id.ends_with(":reference") {
                    let base_name = id.strip_suffix(":reference").unwrap();
                    // Find the corresponding optimized function
                    if let Some(opt_func) = module
                        .functions
                        .iter()
                        .find(|f| f.name != func.name && f.stable_id() == Some(base_name))
                    {
                        pairs.push((opt_func.name.clone(), func.name.clone()));
                    }
                }
            }
        }
    }
    pairs
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

fn extract_source_function_name(test_name: &str, prefix: &str) -> Option<String> {
    let rest = test_name.strip_prefix(prefix)?;
    // test_add_0 → "add"  (strip trailing _N for examples)
    // prop_snap_in_scale → "snap_in_scale"
    if let Some(pos) = rest.rfind('_') {
        let suffix = &rest[pos + 1..];
        if suffix.chars().all(|c| c.is_ascii_digit()) {
            return Some(rest[..pos].to_string());
        }
    }
    Some(rest.to_string())
}

fn extract_req_tags(annotations: &[Annotation]) -> Vec<String> {
    annotations
        .iter()
        .filter_map(|a| match a {
            Annotation::ReqTag(tag) => Some(tag.clone()),
            _ => None,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use speclang_ir::expr::{Block, Expr, Literal, Stmt};
    use speclang_ir::module::{Annotation, Function, Module, Param};
    use speclang_ir::types::Type;

    fn make_test_module() -> Module {
        let mut m = Module::new(vec!["music".to_string(), "scale".to_string()]);

        // Example test: test_snap_0
        m.functions.push(Function {
            name: "test_snap_0".to_string(),
            params: vec![],
            return_type: Type::unit(),
            effects: vec![],
            contracts: vec![],
            body: Block {
                stmts: vec![Stmt::Assert {
                    cond: Expr::BinOp {
                        op: BinOp::Eq,
                        lhs: Box::new(Expr::Call {
                            func: vec!["snap".to_string()],
                            args: vec![Expr::Literal(Literal::Int(12))],
                        }),
                        rhs: Box::new(Expr::Literal(Literal::Int(1))),
                    },
                    message: "example failed".to_string(),
                }],
                expr: None,
            },
            annotations: vec![Annotation::ReqTag("REQ-003".to_string())],
        });

        // Property test: prop_snap_in_scale
        m.functions.push(Function {
            name: "prop_snap_in_scale".to_string(),
            params: vec![
                Param {
                    name: "n".to_string(),
                    ty: Type::int(),
                },
                Param {
                    name: "s".to_string(),
                    ty: Type::Generic {
                        name: vec!["Set".to_string()],
                        args: vec![Type::int()],
                    },
                },
            ],
            return_type: Type::unit(),
            effects: vec![],
            contracts: vec![],
            body: Block {
                stmts: vec![Stmt::Assert {
                    cond: Expr::Literal(Literal::Bool(true)),
                    message: "property failed".to_string(),
                }],
                expr: None,
            },
            annotations: vec![Annotation::ReqTag("REQ-002".to_string())],
        });

        // Regular function (not a test)
        m.functions.push(Function {
            name: "snap".to_string(),
            params: vec![Param {
                name: "note".to_string(),
                ty: Type::int(),
            }],
            return_type: Type::int(),
            effects: vec![],
            contracts: vec![],
            body: Block {
                stmts: vec![],
                expr: Some(Box::new(Expr::Var("note".to_string()))),
            },
            annotations: vec![],
        });

        m
    }

    #[test]
    fn extract_tests_finds_examples_and_props() {
        let m = make_test_module();
        let tests = extract_tests(&m);
        assert_eq!(tests.len(), 2);
        assert_eq!(tests[0].kind, TestKind::Example);
        assert_eq!(tests[1].kind, TestKind::Property);
    }

    #[test]
    fn extract_tests_gets_source_function() {
        let m = make_test_module();
        let tests = extract_tests(&m);
        assert_eq!(tests[0].source_function, Some("snap".to_string()));
        assert_eq!(
            tests[1].source_function,
            Some("snap_in_scale".to_string())
        );
    }

    #[test]
    fn extract_tests_gets_req_tags() {
        let m = make_test_module();
        let tests = extract_tests(&m);
        assert_eq!(tests[0].req_tags, vec!["REQ-003"]);
        assert_eq!(tests[1].req_tags, vec!["REQ-002"]);
    }

    #[test]
    fn generate_oracle_test_creates_assertion() {
        let params = vec![
            Param {
                name: "x".to_string(),
                ty: Type::i32(),
            },
        ];
        let func = generate_oracle_test("fast_snap", "ref_snap", &params, &Type::i32());
        assert_eq!(func.name, "oracle_fast_snap");
        assert_eq!(func.params.len(), 1);
        assert!(matches!(&func.body.stmts[0], Stmt::Assert { .. }));
    }

    #[test]
    fn generate_test_harness_wraps_tests() {
        let m = make_test_module();
        let tests = extract_tests(&m);
        let harness = generate_test_harness(&m.name, &tests);
        assert_eq!(harness.name, vec!["music", "scale", "tests"]);
        assert_eq!(harness.functions.len(), 2);
    }

    #[test]
    fn requirement_coverage_maps_tags() {
        let m = make_test_module();
        let tests = extract_tests(&m);
        let coverage = requirement_coverage(&tests);
        assert_eq!(coverage.len(), 2);
        let req002 = coverage.iter().find(|(k, _)| k == "REQ-002").unwrap();
        assert_eq!(req002.1, vec!["prop_snap_in_scale"]);
        let req003 = coverage.iter().find(|(k, _)| k == "REQ-003").unwrap();
        assert_eq!(req003.1, vec!["test_snap_0"]);
    }

    #[test]
    fn oracle_test_asserts_equality() {
        let params = vec![
            Param {
                name: "a".to_string(),
                ty: Type::int(),
            },
            Param {
                name: "b".to_string(),
                ty: Type::int(),
            },
        ];
        let func = generate_oracle_test("optimized", "reference", &params, &Type::int());
        match &func.body.stmts[0] {
            Stmt::Assert { cond, message } => {
                assert!(message.contains("oracle mismatch"));
                match cond {
                    Expr::BinOp { op, .. } => assert_eq!(*op, BinOp::Eq),
                    other => panic!("Expected BinOp(Eq), got {:?}", other),
                }
            }
            other => panic!("Expected Assert, got {:?}", other),
        }
    }

    #[test]
    fn empty_module_yields_no_tests() {
        let m = Module::new(vec!["empty".to_string()]);
        let tests = extract_tests(&m);
        assert!(tests.is_empty());
    }
}
